# Generated by Django 5.2.7 on 2025-11-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('relatorio', '0011_delete_detalherecarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto de recarga', max_length=100, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço unitário do produto', max_digits=10, verbose_name='Preço Unitário')),
                ('inicio', models.PositiveIntegerField(default=0, help_text='Quantidade disponível no início do dia', verbose_name='Quantidade Inicial')),
                ('vendidas', models.PositiveIntegerField(default=0, help_text='Quantidade vendida durante o dia', verbose_name='Quantidade Vendida')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, help_text='Valor total das vendas (vendidas × preço)', max_digits=12, verbose_name='Total de Vendas')),
                ('resto', models.PositiveIntegerField(default=0, help_text='Quantidade que sobrou no final do dia', verbose_name='Quantidade Restante')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_recargas', to='relatorio.relatoriodiario', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Detalhe de Recarga',
                'verbose_name_plural': 'Detalhes de Recargas',
                'db_table': 'detalhes_recargas',
                'ordering': ['nome'],
            },
        ),
    ]
