# Generated by Django 5.2.7 on 2025-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_recarga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recarga',
        ),
    ]
