# Generated by Django 5.2.7 on 2025-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_delete_recarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('vendidas', models.IntegerField(default=0)),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('resto', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='recargas/')),
            ],
        ),
    ]
