# Generated by Django 5.2.7 on 2025-11-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('tpa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TPA')),
                ('dstv', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DSTV')),
                ('inicio_dstv', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INICIO DA DSTV')),
                ('resto_dstv', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA DSTV')),
                ('zap', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ZAP')),
                ('resto_zap', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA ZAP')),
                ('unitel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='UNITEL')),
                ('resto_unitel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA UNITEL')),
                ('africell', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='AFRICEL')),
                ('resto_africell', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA AFRICEL')),
                ('recargas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RECARGAS')),
                ('acc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ACC')),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='TOTAL GERAL')),
                ('dm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DM')),
                ('moedas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MOEDAS')),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='GASTOS')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório Diário',
                'verbose_name_plural': 'Relatórios Diários',
                'ordering': ['-data'],
            },
        ),
    ]
