# Generated by Django 5.2.7 on 2025-11-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='recargas',
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='recargas_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTAL RECARGAS'),
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Recarga')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('inicio', models.PositiveIntegerField(default=0, verbose_name='Início')),
                ('vendidas', models.PositiveIntegerField(default=0, verbose_name='Vendidas')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Vendas')),
                ('resto', models.PositiveIntegerField(default=0, verbose_name='Resto')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='relatorio.relatoriodiario')),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
