# Generated by Django 5.2.7 on 2025-11-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_remove_relatoriodiario_recargas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='recargas_total',
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='recargas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RECARGAS'),
        ),
        migrations.DeleteModel(
            name='Recarga',
        ),
    ]
