# Generated by Django 5.2.7 on 2025-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_remove_relatoriodiario_recargas_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodiario',
            name='observacao_falta',
            field=models.TextField(blank=True, help_text='Observação obrigatória quando há falta de dinheiro no caixa', null=True, verbose_name='Observação da Falta'),
        ),
        migrations.AlterField(
            model_name='relatoriodiario',
            name='total_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTAL GERAL'),
        ),
    ]
