# Generated by Django 5.2.7 on 2025-11-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0004_relatoriodiario_observacao_falta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='inicio_dstv',
        ),
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='resto_africell',
        ),
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='resto_dstv',
        ),
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='resto_unitel',
        ),
        migrations.RemoveField(
            model_name='relatoriodiario',
            name='resto_zap',
        ),
        migrations.AlterField(
            model_name='relatoriodiario',
            name='observacao_falta',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Falta'),
        ),
    ]
