# Generated by Django 5.2.7 on 2025-11-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0005_remove_relatoriodiario_inicio_dstv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodiario',
            name='inicio_dstv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INICIO DA DSTV'),
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='resto_africell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA AFRICEL'),
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='resto_dstv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA DSTV'),
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='resto_unitel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA UNITEL'),
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='resto_zap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RESTO DA ZAP'),
        ),
        migrations.AlterField(
            model_name='relatoriodiario',
            name='observacao_falta',
            field=models.TextField(blank=True, help_text='Observação obrigatória quando há falta de dinheiro no caixa', null=True, verbose_name='Observação da Falta'),
        ),
    ]
