# Generated by Django 5.2.7 on 2025-11-11 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_alter_loja_provincia_venda'),
        ('relatorio', '0006_relatoriodiario_inicio_dstv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriodiario',
            options={'ordering': ['-data', 'loja'], 'verbose_name': 'Relatório Diário', 'verbose_name_plural': 'Relatórios Diários'},
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_diarios', to='lojas.loja', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='relatoriodiario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_diarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário/Gerente'),
        ),
        migrations.AlterField(
            model_name='relatoriodiario',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterUniqueTogether(
            name='relatoriodiario',
            unique_together={('loja', 'data')},
        ),
    ]
