# Generated by Django 5.2.7 on 2025-11-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0007_alter_relatoriodiario_options_relatoriodiario_loja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('inicio', models.PositiveIntegerField(default=0, verbose_name='Quantidade Inicial')),
                ('vendidas', models.PositiveIntegerField(default=0, verbose_name='Quantidade Vendida')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Vendas')),
                ('resto', models.PositiveIntegerField(default=0, verbose_name='Quantidade Restante')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_recargas', to='relatorio.relatoriodiario')),
            ],
            options={
                'verbose_name': 'Detalhe de Recarga',
                'verbose_name_plural': 'Detalhes de Recargas',
            },
        ),
    ]
