# Generated by Django 5.2.7 on 2025-11-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0008_detalherecarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalherecarga',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_recargas', to='relatorio.relatoriodiario', verbose_name='Relatório'),
        ),
        migrations.AlterModelTable(
            name='detalherecarga',
            table='detalhes_recargas',
        ),
    ]
