# Generated by Django 5.2.7 on 2025-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0009_alter_detalherecarga_preco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalherecarga',
            options={'ordering': ['nome'], 'verbose_name': 'Detalhe de Recarga', 'verbose_name_plural': 'Detalhes de Recargas'},
        ),
        migrations.AddField(
            model_name='detalherecarga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='detalherecarga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='inicio',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade disponível no início do dia', verbose_name='Quantidade Inicial'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='nome',
            field=models.CharField(help_text='Nome do produto de recarga', max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço unitário do produto', max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='resto',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade que sobrou no final do dia', verbose_name='Quantidade Restante'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='total_vendas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total das vendas (vendidas × preço)', max_digits=12, verbose_name='Total de Vendas'),
        ),
        migrations.AlterField(
            model_name='detalherecarga',
            name='vendidas',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade vendida durante o dia', verbose_name='Quantidade Vendida'),
        ),
    ]
