# Generated by Django 5.2.7 on 2025-11-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0010_alter_detalherecarga_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalheRecarga',
        ),
    ]
