# Generated by Django 5.2.7 on 2025-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0011_delete_detalherecarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodiario',
            name='detalhes_recargas',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes das Recargas em JSON'),
        ),
    ]
