# Generated by Django 4.2.7 on 2026-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0012_relatoriodiario_detalhes_recargas'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodiario',
            name='inicio_africell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INICIO DA AFRICEL'),
        ),
    ]
