# Generated by Django 5.2.7 on 2025-11-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0011_alter_estoqueloja_loja_alter_estoqueloja_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, verbose_name='Tipo de Período')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('total_vendas_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Vendas Produtos')),
                ('total_vendas_recargas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Vendas Recargas')),
                ('total_vendas_geral', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Vendas Geral')),
                ('quantidade_vendas_produtos', models.PositiveIntegerField(default=0, verbose_name='Quantidade Vendas Produtos')),
                ('quantidade_vendas_recargas', models.PositiveIntegerField(default=0, verbose_name='Quantidade Vendas Recargas')),
                ('total_transacoes', models.PositiveIntegerField(default=0, verbose_name='Total Transações')),
                ('custos_operacionais', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custos Operacionais')),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Lucro Bruto')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('status', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutro', 'Neutro')], default='neutro', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancos', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Balanço',
                'verbose_name_plural': 'Balanços',
                'ordering': ['-data_inicio', 'loja'],
                'indexes': [models.Index(fields=['loja', 'periodo_tipo', 'data_inicio'], name='balanco_bal_loja_id_e630dc_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='balanco_bal_data_in_9bf971_idx')],
                'unique_together': {('loja', 'periodo_tipo', 'data_inicio')},
            },
        ),
    ]
