# Generated by Django 5.2.7 on 2025-11-29 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='balanco',
            name='balanco_bal_loja_id_e630dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='balanco',
            name='balanco_bal_data_in_9bf971_idx',
        ),
        migrations.AddField(
            model_name='balanco',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balanco',
            name='descricao_periodo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição do Período'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='detalhes_produtos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='balanco',
            name='detalhes_recargas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='balanco',
            name='detalhes_relatorios_diarios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='balanco',
            name='detalhes_vendas_diarias',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='balanco',
            name='detalhes_vendedores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='balanco',
            name='diferenca_caixa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_acc_relatorios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_africell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_arrecadado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_dm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_dstv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_geral_relatorios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_inicio_dstv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_moedas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_recargas_relatorios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_resto_africell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_resto_dstv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_resto_unitel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_resto_zap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_tpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_unitel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_zap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='custos_operacionais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='lucro_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='periodo_tipo',
            field=models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], max_length=15, verbose_name='Tipo de Período'),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='quantidade_vendas_produtos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='quantidade_vendas_recargas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='status',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutro', 'Neutro')], default='neutro', max_length=10),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='total_transacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='total_vendas_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='total_vendas_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='total_vendas_recargas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
