# Generated by Django 5.2.7 on 2025-12-02 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco', '0002_remove_balanco_balanco_bal_loja_id_e630dc_idx_and_more'),
        ('lojas', '0011_alter_estoqueloja_loja_alter_estoqueloja_produto_and_more'),
        ('produtos', '0004_recarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Referência')),
                ('tipo_movimento', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('devolucao', 'Devolução'), ('transferencia', 'Transferência')], max_length=15, verbose_name='Tipo de Movimento')),
                ('quantidade_anterior', models.PositiveIntegerField(default=0, verbose_name='Quantidade Anterior')),
                ('quantidade_movimento', models.PositiveIntegerField(default=0, verbose_name='Quantidade Movimentada')),
                ('quantidade_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Unitário')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Total')),
                ('preco_venda_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda Unitário')),
                ('motivo_tipo', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Motivo')),
                ('motivo_detalhado', models.TextField(blank=True, verbose_name='Motivo Detalhado')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Documento de Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja', verbose_name='Loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='lojas.venda', verbose_name='Venda Relacionada')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['referencia'], name='balanco_mov_referen_8a6c75_idx'), models.Index(fields=['produto', 'criado_em'], name='balanco_mov_produto_3c148e_idx'), models.Index(fields=['loja', 'tipo_movimento'], name='balanco_mov_loja_id_e75097_idx'), models.Index(fields=['criado_em'], name='balanco_mov_criado__4828ee_idx')],
            },
        ),
    ]
