# Generated by Django 4.2.7 on 2026-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco', '0003_movimentoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='detalhes_relatorios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='balanco',
            name='total_inicio_africell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
