# Generated by Django 5.2.7 on 2025-11-10 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Loja')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('provincia', models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cuando-Cubango', 'Cuando-Cubango'), ('Cuanza-Norte', 'Cuanza-Norte'), ('Cuanza-Sul', 'Cuanza-Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Luanda', 'Luanda'), ('Lunda-Norte', 'Lunda-Norte'), ('Lunda-Sul', 'Lunda-Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uíge', 'Uíge'), ('Zaire', 'Zaire')], max_length=50, verbose_name='Província')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('gerentes', models.ManyToManyField(related_name='lojas_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Gerentes')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='EstoqueLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Estoque da Loja',
                'verbose_name_plural': 'Estoques das Lojas',
                'unique_together': {('loja', 'produto')},
            },
        ),
    ]
