# Generated by Django 5.2.7 on 2025-11-10 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_alter_loja_provincia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='provincia',
            field=models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cuando-Cubango', 'Cuando-Cubango'), ('Cuanza-Norte', 'Cuanza-Norte'), ('Cuanza-Sul', 'Cuanza-Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Luanda', 'Luanda'), ('Lunda-Norte', 'Lunda-Norte'), ('Lunda-Sul', 'Lunda-Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uíge', 'Uíge'), ('Zaire', 'Zaire')], max_length=50, verbose_name='Província'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='lojas.estoqueloja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
