# Generated by Django 5.2.7 on 2025-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_alter_loja_provincia_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='provincia',
            field=models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela')], max_length=50, verbose_name='Província'),
        ),
    ]
