# Generated by Django 5.2.7 on 2025-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0004_alter_loja_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='provincia',
            field=models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cuando-Cubango', 'Cuando-Cubango'), ('Cuanza-Norte', 'Cuanza-Norte'), ('Cuanza-Sul', 'Cuanza-Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Luanda', 'Luanda'), ('Lunda-Norte', 'Lunda-Norte'), ('Lunda-Sul', 'Lunda-Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uíge', 'Uíge'), ('Zaire', 'Zaire')], max_length=50, verbose_name='Província'),
        ),
    ]
