# Generated by Django 5.2.7 on 2025-11-11 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_alter_loja_provincia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['estoque', 'data_venda'], name='lojas_venda_estoque_b5b29e_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['data_venda'], name='lojas_venda_data_ve_3155ca_idx'),
        ),
    ]
