# Generated by Django 5.2.7 on 2025-11-12 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0006_venda_lojas_venda_estoque_b5b29e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='provincia',
            field=models.CharField(choices=[('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cuando-Cubango', 'Cuando-Cubango'), ('Cuanza-Norte', 'Cuanza-Sul'), ('Cuanza-Sul', 'Cuanza-Sul'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Luanda', 'Luanda'), ('Lunda-Norte', 'Lunda-Norte'), ('Lunda-Sul', 'Lunda-Sul'), ('Malanje', 'Malanje'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uíge', 'Uíge'), ('Zaire', 'Zaire')], max_length=50, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['vendedor', 'data_venda'], name='lojas_venda_vendedo_fcc8ab_idx'),
        ),
    ]
