# Generated by Django 5.2.7 on 2025-11-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0008_remove_venda_lojas_venda_vendedo_fcc8ab_idx_and_more'),
        ('produtos', '0004_recarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja', verbose_name='Loja')),
                ('recarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.recarga', verbose_name='Recarga')),
            ],
            options={
                'verbose_name': 'Estoque de Recarga',
                'verbose_name_plural': 'Estoques de Recargas',
                'unique_together': {('loja', 'recarga')},
            },
        ),
    ]
