# Generated by Django 5.2.7 on 2025-11-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0009_estoquerecarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venda',
            name='lojas_venda_estoque_b5b29e_idx',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='estoque',
        ),
        migrations.AddField(
            model_name='venda',
            name='estoque_loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_produto', to='lojas.estoqueloja', verbose_name='Estoque do Produto'),
        ),
        migrations.AddField(
            model_name='venda',
            name='estoque_recarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_recarga', to='lojas.estoquerecarga', verbose_name='Estoque da Recarga'),
        ),
        migrations.AddField(
            model_name='venda',
            name='item_type',
            field=models.CharField(choices=[('produto', 'Produto'), ('recarga', 'Recarga')], default='produto', max_length=10, verbose_name='Tipo de Item'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade Vendida'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['estoque_loja', 'data_venda'], name='lojas_venda_estoque_6d7e79_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['estoque_recarga', 'data_venda'], name='lojas_venda_estoque_44e7b4_idx'),
        ),
    ]
