# Generated by Django 5.2.7 on 2025-11-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0010_remove_venda_lojas_venda_estoque_b5b29e_idx_and_more'),
        ('produtos', '0004_recarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueloja',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja'),
        ),
        migrations.AlterField(
            model_name='estoqueloja',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='estoqueloja',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
