# Generated by Django 4.2.7 on 2026-03-23 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_recarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0011_alter_estoqueloja_loja_alter_estoqueloja_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('devolucao', 'Devolução')], max_length=20, verbose_name='Tipo')),
                ('tipo_item', models.CharField(choices=[('produto', 'Produto'), ('recarga', 'Recarga')], max_length=20, verbose_name='Tipo de Item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('quantidade_anterior', models.PositiveIntegerField(default=0, verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.PositiveIntegerField(default=0, verbose_name='Quantidade Nova')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('parcial', 'Devolução Parcial'), ('devolvida', 'Totalmente Devolvida')], default='normal', max_length=20, verbose_name='Status da Venda'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='lojas_venda_status_672f1d_idx'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='lojas.loja'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='recarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.recarga'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes', to='lojas.venda'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['loja', 'tipo_movimentacao'], name='lojas_movim_loja_id_1e29f5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['data_movimentacao'], name='lojas_movim_data_mo_bd9ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['venda'], name='lojas_movim_venda_i_49f353_idx'),
        ),
    ]
