# Generated by Django 5.0.14 on 2026-09-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0012_movimentacaoestoque_venda_status_and_more'),
        ('produtos', '0005_produto_ativo_recarga_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='estoqueloja',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='estoquerecarga',
            name='recarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.recarga', verbose_name='Recarga'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='recarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.recarga'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='estoque_loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_produto', to='lojas.estoqueloja', verbose_name='Estoque do Produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='estoque_recarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_recarga', to='lojas.estoquerecarga', verbose_name='Estoque da Recarga'),
        ),
    ]
