# Generated by Django 5.0.14 on 2026-09-16 09:40

import django.db.models.deletion
import django.utils.timezone
import faturacao.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('nif', models.CharField(db_index=True, max_length=20, validators=[faturacao.models.validar_nif_angolano], verbose_name='NIF')),
                ('regime_iva', models.CharField(choices=[('GERAL', 'Regime Geral'), ('SIMPLIFICADO', 'Regime Simplificado'), ('EXCLUSAO', 'Regime de Exclusão')], default='GERAL', max_length=15, verbose_name='Regime de IVA')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(default='Luanda, Angola', max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(default='Luanda', max_length=100, verbose_name='Cidade')),
                ('provincia', models.CharField(default='Luanda', max_length=50, verbose_name='Província')),
                ('pais', models.CharField(default='AO', max_length=2, verbose_name='País')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente Fiscal',
                'verbose_name_plural': 'Clientes Fiscais',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(default='MAJOBFIL COMÉRCIO E SERVIÇOS, LDA', max_length=200, verbose_name='Razão Social')),
                ('nome_comercial', models.CharField(default='MAJOBFIL', max_length=200, verbose_name='Nome Comercial')),
                ('nif', models.CharField(default='5412345678', max_length=20, validators=[faturacao.models.validar_nif_angolano], verbose_name='NIF do Emitente')),
                ('regime_iva', models.CharField(choices=[('GERAL', 'Regime Geral'), ('SIMPLIFICADO', 'Regime Simplificado'), ('EXCLUSAO', 'Regime de Exclusão')], default='GERAL', max_length=15, verbose_name='Regime de IVA')),
                ('endereco', models.CharField(default='Luanda, Angola', max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(default='Luanda', max_length=100, verbose_name='Cidade')),
                ('provincia', models.CharField(default='Luanda', max_length=50, verbose_name='Província')),
                ('pais', models.CharField(default='AO', max_length=2, verbose_name='País')),
                ('telefone', models.CharField(default='+244 923 000 000', max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(default='contato@majobfil.ao', max_length=254, verbose_name='Email')),
                ('numero_certificado_agt', models.CharField(default='000/AGT/2026', max_length=50, verbose_name='N.º Certificado do Software AGT')),
                ('nif_produtor_software', models.CharField(default='5412345678', max_length=20, verbose_name='NIF do Produtor de Software')),
                ('nome_software', models.CharField(default='MAJOBFIL ERP/POS', max_length=100, verbose_name='Nome do Software')),
                ('versao_software', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão do Software')),
                ('chave_privada_path', models.CharField(default='certs/chave_privada_agt.pem', max_length=255, verbose_name='Caminho da Chave Privada PEM')),
                ('chave_publica_path', models.CharField(default='certs/chave_publica_agt.pem', max_length=255, verbose_name='Caminho da Chave Pública PEM')),
                ('versao_chave', models.PositiveIntegerField(default=1, verbose_name='Versão da Chave')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa (AGT)',
                'verbose_name_plural': 'Configurações da Empresa (AGT)',
            },
        ),
        migrations.CreateModel(
            name='MotivoIsencaoIVA',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código AGT')),
                ('mencao_legal', models.CharField(max_length=255, verbose_name='Menção Legal')),
                ('descricao', models.TextField(verbose_name='Descrição Jurídica')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motivo de Isenção de IVA (AGT)',
                'verbose_name_plural': 'Motivos de Isenção de IVA (AGT)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SerieFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('tipo_documento', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito')], max_length=2, verbose_name='Tipo de Documento')),
                ('ano', models.PositiveIntegerField(default=2026, verbose_name='Ano Fiscal')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último Número Emitido')),
                ('ultimo_hash', models.TextField(blank=True, default='', verbose_name='Último Hash Emitido (Base64)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Série Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Série Fiscal',
                'verbose_name_plural': 'Séries Fiscais',
                'ordering': ['tipo_documento', 'serie', '-ano'],
                'unique_together': {('serie', 'tipo_documento', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.PositiveIntegerField(verbose_name='Número Sequencial')),
                ('numero_fatura', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número da Fatura')),
                ('status', models.CharField(choices=[('N', 'Normal'), ('A', 'Anulada'), ('R', 'Retificada')], default='N', max_length=1, verbose_name='Estado')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('system_entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora de Gravação no Sistema')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('emitente_nome', models.CharField(max_length=200, verbose_name='Razão Social Emitente')),
                ('emitente_nif', models.CharField(max_length=20, verbose_name='NIF Emitente')),
                ('emitente_endereco', models.CharField(max_length=255, verbose_name='Endereço Emitente')),
                ('emitente_regime_iva', models.CharField(max_length=20, verbose_name='Regime IVA Emitente')),
                ('cliente_nome', models.CharField(max_length=200, verbose_name='Razão Social Cliente')),
                ('cliente_nif', models.CharField(max_length=20, verbose_name='NIF Cliente')),
                ('cliente_endereco', models.CharField(max_length=255, verbose_name='Endereço Cliente')),
                ('total_incidencia', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Incidência Líquida')),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de IVA Liquidado')),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Descontos')),
                ('total_retencao_fonte', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retenção na Fonte')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Bruto / A Pagar')),
                ('hash_anterior', models.TextField(blank=True, verbose_name='Hash da Fatura Anterior')),
                ('dados_para_hash', models.TextField(verbose_name='String de Entrada da Assinatura')),
                ('hash_assinatura', models.TextField(verbose_name='Assinatura Digital RSA-SHA1 (Base64)')),
                ('hash_curto', models.CharField(max_length=150, verbose_name='Hash de 4 Caracteres (Exibição)')),
                ('versao_chave', models.PositiveIntegerField(default=1, verbose_name='Versão da Chave Pública AGT')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='faturacao.clientefiscal')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('serie_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='faturacao.seriefiscal')),
            ],
            options={
                'verbose_name': 'Fatura Fiscal',
                'verbose_name_plural': 'Faturas Fiscais',
                'ordering': ['-system_entry_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linha', models.PositiveIntegerField(verbose_name='N.º da Linha')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Código do Artigo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Produto/Serviço')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário (s/ IVA)')),
                ('desconto_linha', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto Comercial')),
                ('tipo_taxa_iva', models.CharField(choices=[('NOR', 'Normal (14%)'), ('RED', 'Reduzida (7% ou 5%)'), ('INT', 'Intermédia'), ('ISE', 'Isenta (0%)'), ('OUT', 'Outros')], default='NOR', max_length=3, verbose_name='Código Taxa')),
                ('taxa_iva', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='Taxa de IVA (%)')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montante do IVA')),
                ('subtotal_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal s/ IVA')),
                ('total_linha', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total c/ IVA')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturacao.fatura')),
                ('motivo_isencao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faturacao.motivoisencaoiva', verbose_name='Motivo de Isenção (Obrigatório se IVA=0)')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
                'ordering': ['fatura', 'numero_linha'],
                'unique_together': {('fatura', 'numero_linha')},
            },
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['numero_fatura'], name='faturacao_f_numero__14a304_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['data_emissao'], name='faturacao_f_data_em_b7b563_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['status'], name='faturacao_f_status_95331a_idx'),
        ),
    ]
